version: '3.8'
services:
    app:
      build: ./app
      command: uvicorn main:app --reload --host 0.0.0.0
      ports:
        - "8000:8000"
      volumes:
        - ./app/:/app
    db:
      image: postgres:14.4-alpine
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      ports:
        - "5432:5432"
